// Code generated by MockGen. DO NOT EDIT.
// Source: services/url_service.go
//
// Generated by this command:
//
//	mockgen -source=services/url_service.go -destination=services/mocks/mock_service.go -package=mock_services
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"
	models "Backend/models"

	gomock "go.uber.org/mock/gomock"
)

// MockUrlServiceInterface is a mock of UrlServiceInterface interface.
type MockUrlServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUrlServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUrlServiceInterfaceMockRecorder is the mock recorder for MockUrlServiceInterface.
type MockUrlServiceInterfaceMockRecorder struct {
	mock *MockUrlServiceInterface
}

// NewMockUrlServiceInterface creates a new mock instance.
func NewMockUrlServiceInterface(ctrl *gomock.Controller) *MockUrlServiceInterface {
	mock := &MockUrlServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUrlServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlServiceInterface) EXPECT() *MockUrlServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateUrl mocks base method.
func (m *MockUrlServiceInterface) CreateUrl(url *models.Url) (*models.ShortUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUrl", url)
	ret0, _ := ret[0].(*models.ShortUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUrl indicates an expected call of CreateUrl.
func (mr *MockUrlServiceInterfaceMockRecorder) CreateUrl(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUrl", reflect.TypeOf((*MockUrlServiceInterface)(nil).CreateUrl), url)
}

// GetUrlByShortUrl mocks base method.
func (m *MockUrlServiceInterface) GetUrlByShortUrl(shortUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrlByShortUrl", shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUrlByShortUrl indicates an expected call of GetUrlByShortUrl.
func (mr *MockUrlServiceInterfaceMockRecorder) GetUrlByShortUrl(shortUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrlByShortUrl", reflect.TypeOf((*MockUrlServiceInterface)(nil).GetUrlByShortUrl), shortUrl)
}
