name: Go CI with Coveralls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache-dependency-path: Backend/go.sum

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run tests and generate coverage
      - name: Run tests
        run: go test -coverprofile=coverage.out ./...

      # Step 5: Install goveralls
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      # Step 6: Send coverage to Coveralls
      - name: Send coverage to Coveralls
        run: goveralls -coverprofile=coverage.out -service=github -repotoken ${{ secrets.COVERALLS_REPO_TOKEN }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
